#!/usr/bin/env bash
# This is a script that displays numbers from 1 to 100
# displays "FizzBuzz" when the number is a multiple of 3 and 5
# displays "Fizz" when the number is a multiple of 3
# displays "Buzz" when the number is a multiple of 5
num=1
while [ $num -le 100 ]; do
	if [ $((num % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((num % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((num % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo "$num"
	fi
	((num++))
done
