#!/usr/bin/env bash
# This is a script that displays the content of the current directory
# In a list format
# where only the part of the name after the first dash is displayed
list="$(ls .)"
for file in $list; do
	if [ -f "$file" ]; then
		file_name=$(echo "$file" | cut -d'-' -f2-)
		echo "$file_name"
	fi
done
