#!/usr/bin/env bash
# This script makes changes to the hosts file
#+ Makes 'localhost' resolve to 127.0.0.2
#+ Makes 'facebook' resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i -e 's/^127\.0\.0\.1[[:space:]]*localhost/127.0.0.2	localhost/' ~/hosts.new
sed -i -e '$a 8.8.8.8	facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
